[package]

name = "rim"
version = "0.0.1"
authors = [ "Mathias Hällman <rim@mths.se>" ]

[[bin]]
name = "rim"

[dependencies.termkey]
git = "git://github.com/mathall/termkey-rs.git"

[dependencies]
bitflags = "*"
term = "*"
unicode-width = "*"
uuid = "*"
